# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PassWin(object):
    def setupUi(self, PassWin):
        PassWin.setObjectName("PassWin")
        PassWin.resize(744, 572)
        PassWin.setStyleSheet("background-color:rgb(85, 85, 127)")
        self.centralwidget = QtWidgets.QWidget(PassWin)
        self.centralwidget.setObjectName("centralwidget")
        self.addPwdBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addPwdBtn.setGeometry(QtCore.QRect(30, 230, 75, 23))
        self.addPwdBtn.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 0, 0);\n"
"}")
        self.addPwdBtn.setObjectName("addPwdBtn")
        self.userLine = QtWidgets.QLineEdit(self.centralwidget)
        self.userLine.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.userLine.setObjectName("userLine")
        self.webLine = QtWidgets.QLineEdit(self.centralwidget)
        self.webLine.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.webLine.setObjectName("webLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.label.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 60, 81, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.passList = QtWidgets.QTableWidget(self.centralwidget)
        self.passList.setGeometry(QtCore.QRect(380, 110, 301, 361))
        self.passList.setAutoFillBackground(False)
        self.passList.setStyleSheet("background-color:rgb(85, 85, 127);")
        self.passList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.passList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.passList.setProperty("showDropIndicator", False)
        self.passList.setObjectName("passList")
        self.passList.setColumnCount(3)
        self.passList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 129, 94))
        self.passList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.passList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.passList.setHorizontalHeaderItem(2, item)
        self.showPass = QtWidgets.QPushButton(self.centralwidget)
        self.showPass.setGeometry(QtCore.QRect(484, 480, 121, 23))
        self.showPass.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 0, 0);\n"
"}")
        self.showPass.setObjectName("showPass")
        self.showPass.clicked.connect(self.load_data)
        self.passLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passLine.setGeometry(QtCore.QRect(10, 200, 113, 20))
        self.passLine.setObjectName("passLine")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_6.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_7.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 180, 47, 13))
        self.label_8.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label_8.setObjectName("label_8")
        PassWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PassWin)
        self.statusbar.setObjectName("statusbar")
        PassWin.setStatusBar(self.statusbar)

        self.retranslateUi(PassWin)
        QtCore.QMetaObject.connectSlotsByName(PassWin)

    def retranslateUi(self, PassWin):
        _translate = QtCore.QCoreApplication.translate
        PassWin.setWindowTitle(_translate("PassWin", "MainWindow"))
        self.addPwdBtn.setText(_translate("PassWin", "Add Password"))
        self.label.setText(_translate("PassWin", "ADD NEW PASSWORD"))
        self.label_3.setText(_translate("PassWin", "PassManager"))
        self.label_4.setText(_translate("PassWin", "List of Password"))
        item = self.passList.horizontalHeaderItem(0)
        item.setText(_translate("PassWin", "Website"))
        item = self.passList.horizontalHeaderItem(1)
        item.setText(_translate("PassWin", "Username"))
        item = self.passList.horizontalHeaderItem(2)
        item.setText(_translate("PassWin", "Password"))
        self.showPass.setText(_translate("PassWin", "Show Passowrds"))
        self.label_6.setText(_translate("PassWin", "Username"))
        self.label_7.setText(_translate("PassWin", "Website"))
        self.label_8.setText(_translate("PassWin", "Password"))
    def load_data(self):
        user_data = [self.webLine.text(),self.userLine.text(),self.passLine.text()]
        data = []
        data.append(user_data)
        row = 0
        self.passList.setRowCount(len(data))
        for eachRow in data:
                self.passList.setItem(row,0,QtWidgets.QTableWidgetItem(eachRow[0]))
                self.passList.setItem(row,1,QtWidgets.QTableWidgetItem(eachRow[1]))
                self.passList.setItem(row,2,QtWidgets.QTableWidgetItem(eachRow[2]))
                row = row + 1 
        print(self.passList.rowCount())
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PassWin = QtWidgets.QMainWindow()
    ui = Ui_PassWin()
    ui.setupUi(PassWin)
    PassWin.show()
    sys.exit(app.exec_())
