# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from passScreen import Ui_PassWin

class Ui_MainWindow(object):
    
    #new window on click
    def pass_screen(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_PassWin()
        self.ui.setupUi(self.window2)
        self.window2.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 468)
        MainWindow.setStyleSheet("background-color:rgb(85, 85, 127)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbtn.setGeometry(QtCore.QRect(130, 280, 75, 23))
        self.loginbtn.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 0, 0);\n"
"}")
        self.loginbtn.setObjectName("loginbtn")
        self.loginbtn.clicked.connect(self.Login_clicked)
        self.loginbtn.clicked.connect(MainWindow.close)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 210, 113, 20))
        self.lineEdit.setObjectName("username")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 130, 113, 20))
        self.lineEdit_2.setObjectName("pass")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 110, 47, 13))
        self.label.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 190, 47, 13))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color:rgb(0, 93, 0);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginbtn.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Usernamel"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "PassManager"))
    
    def Login_clicked(self):
        username = ""
        password = ""
        typed_pwd = self.lineEdit.text()
        typed_user = self.lineEdit_2.text()
        print(typed_user,typed_pwd)
        if typed_user == username and typed_pwd == password:
                self.pass_screen()
        else:
                print("wrong input")
                

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
